# Generated by Django 4.1.4 on 2023-01-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('f', 'Free'), ('p', 'Premium')], max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Applications and Versions',
            },
        ),
    ]
