# Generated by Django 4.1.4 on 2023-01-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.FloatField(help_text='Application version must be update [0.*] or upgrade [*.0]')),
                ('description', models.TextField(blank=True, help_text='Detailed down description', null=True)),
                ('category', models.CharField(choices=[('f', 'Free'), ('p', 'Premium')], max_length=1)),
                ('operating_system', models.CharField(choices=[('w', 'Windows'), ('l', 'Linux'), ('m', 'Mac')], max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Applications and Versions',
            },
        ),
    ]
